pull_request_rules:
  - name: Automatic merge on all check pass
    conditions:
      - author=KEINOS
      - base=main
      - title~=^Changes
      - files=VERSION_SQLite3.txt
      - "#files=1"
      - check-success=Azure Container Scan / azure
      - check-success=Snyk Docker Scan / snyk (pull_request)
      - check-success=Code scanning results / Snyk Container
      - check-success=[container-scan] keinos/sqlite3:test
    actions:
      merge:
        method: merge
