pull_request_rules:
  - name: Automatic merge on all check pass
    conditions:
      - author=KEINOS
      - base=master
      - title~=^Changes
      - files=VERSION_SQLite3.txt
      - "#files=1"
      - check-success="azure"
      - check-success="snyk"
      - check-success="Snyk Container"
      - check-success="[container-scan] keinos/sqlite3:test"
    actions:
      merge:
        method: merge
